services:
    postgres:
        image: postgres:15-alpine
        container_name: grid07-postgres
        environment:
            POSTGRES_USER: grid07
            POSTGRES_PASSWORD: password
            POSTGRES_DB: assignment_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: grid07-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped

volumes:
    postgres_data:
    redis_data:
